services:
  db:
    image: postgres:17-alpine  # 修改这里，匹配你本地已有的镜像
    container_name: codehub_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: codehub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: